
      
name: NPM & WebP

# 在 Release 发布时 或手动执行

on:

  release:

     types:

       - published

  push:

  workflow_dispatch:

jobs:

  publish-npm:

    runs-on: ubuntu-latest

    # Clone 仓库

    steps:

      - name: Checkout

        uses: actions/checkout@v2

        with:

          ref: main

      # 安装 Node.js    

      - name: Setup Node.js 16.10.0

        uses: actions/setup-node@master

        with:

          node-version: "16.10.0"

        

          

          

      - name: Push

        run: |

         npm install node-fetch@2.6.0 -s

         npm install js-md5 -s

         node update.js

          

          

        

      - name: npm publish

        uses: JS-DevTools/npm-publish@v1

        with:

          token: ${{ secrets.NPM_TOKEN }}
