name: auto push

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    # 1. 获取源码
    - name: Checkout
      uses: actions/checkout@v3 # 使用 actions/checkout@v3
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？
    # 2. 配置环境
    - name: Setup Node.js 12.10.0
      uses: actions/setup-node@master
      with:
        node-version: "12.10.0"

    - name: Push
      run: |
        git add -A
        git commit -m "Publish"
        git push origin main
                
    - name: Publish Package
      run: |
        git config --global user.email "2015078351@qq.com"
        git config --global user.name "Bytelv"
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM}}
        
    - name: Refresh NPM Cache
      run: >
        curl -X PUT "https://registry.npmmirror.com/lvbyte-cdn/sync?publish=false&nodeps=false"
        

      
