name: auto push

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    # 1. 获取源码
    - name: Checkout
      uses: actions/checkout@v3 # 使用 actions/checkout@v3
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？
    # 2. 配置环境
    - name: Setup Node.js 12.10.0
      uses: actions/setup-node@master
      with:
        node-version: "12.10.0"
                
    - name: npm publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM }}
        
    - name: Refresh NPM Cache
      run: >
        curl -X PUT "https://registry.npmmirror.com/lvbyte-cdn/sync?publish=false&nodeps=false"
        
    - name: Install dependencies
      run: npm i semantic-release
      env: 
        INPUT_TOKEN: ''
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM }}
      run: npx semantic-release
      
      
