name: NPM & WebP

# 在 Release 发布时 或手动执行

on:
  release:
     types:
       - published

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # Clone 仓库
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      # 安装 Node.js    
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
        
          
      # 发布 NPM 包
      - name: Publish Package
        run: |
          git config --global user.email "2015078351@qq.com"
          git config --global user.name "Bytelv"
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
          
          
      - name: Push
        run: |
          git add -A
          git commit -m "Publish"
          git push origin main
